### ISSUE TITLE
Menu button

### ISSUE THREAD

**Issue by timchenj5** [GovAlta/ui-components#1328]
# Acceptance Criteria

[Design and documentation from the design system here](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Component-library-%7C-DDD?type=design&node-id=41625-336313&mode=design&t=FcHchTzFWliuA2vk-4)

1. Behaviour of the component:
    * onClick of the button popover opens
    * clicking/tapping outside of the button or an option inside closes the popover
    * options inside are clickable elements that will do an action
    * chevron icon switches from down to up when open
2. Intital release will not be inclusive of design system website documentation
3. Test in web-components/Dropdown.spec.ts - "searches by partial filter and click to select option" is rewritten as a browser test

## Accessibility
* **Screen reader announcement** When the button receives focus reader will announce "[menu button label] menu button, collapsed"
* **Press Enter** while focused on the menu button to open/close the menu; when navigating, selects the focused item
* **Press Spacebar** while focused on the menu button to open/close the menu; when navigating, selects the focused item
* **Press Arrow Up** to move focus to the previous item
* **Press Arrow Down** to move focus to the next item
* **Press Home** to move focus to the first item
* **Press End** to move focus to the last item
* **Press Escape** to close the menu
* **Press Tab** to move focus to the next focusable element
* **Press Shift + Tab** to move focus to the previous focusable element

**Comment by ArakTaiRoth** [comment]
This can basically be done now with the following code:
```html
<goab-popover [target]="target" [padded]="false">
  <a href="#" class="popover-link">Adjourned in Court</a>
  <a href="#" class="popover-link">Adjourned by consent</a>
  <a href="#" class="popover-link">Heard and adjourned</a>
  <a href="#" class="popover-link">Justice seized (to commercial)</a>
  <ng-template #target>
    <goab-button trailingIcon="caret-down">Enter Result</goab-button>
  </ng-template>
</goab-popover>
```

```css
a.popover-link {
  color: var(--goa-color-text-default);
  display: block;
  padding: var(--goa-app-header-padding-nav-item-in-menu);
  text-decoration: none;
  border-bottom: 1px solid #000;
}

a.popover-link:hover {
  color: var(--goa-app-header-color-text-nav-item-hover);
  background-color: var(--goa-app-header-color-bg-nav-item-child-hover);
}

a.popover-link:last-of-type {
  border-bottom: none;
}
```
