### ISSUE TITLE
Headers: Mobile h3 on website has incorrect styling

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#2026]
# Info

On the website, all `h3` tags when seen in mobile, have the following styling applied to them:

```css
@media screen and (max-width: 623px) {
  h3 {
    font: var(--goa-typography-body-m);
  }
}
```

This is incorrect and should be removed

## Acceptance Criteria:

1. `h3` tags on mobile should have the same styling applied to them as on desktop
