### ISSUE TITLE
Privacy Portal (SideMenu): Can't change the colour of `a`

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#2252]
# Info

Reported by Chase Buhler

We have a CSS rule in `SideMenu.svelte`:
```css
:global(::slotted(a)),
:global(::slotted(a:visited)) {
  /* required to override base styles */
  color: var(--goa-color-text-default) !important;
  display: block;
  font: var(--goa-typography-body-m);
  padding: 0.5rem 1rem 0.5rem 2rem;
  text-decoration: none;
}
```
The offending issue is the `color` property, which is tagged with `!important`. This makes it impossible for teams to style the `color` of their `a` tags inside the SideMenu on a per-link basis, no matter the order of operations in CSS or not. We need to figure out how to apply this style, without using `!important`.

## Acceptance Criteria:

1. Apply `color` property to `a` tags in the Side Menu component, without using `!important`
