### ISSUE TITLE
Badge: goab-badge is out of alignment

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#2513]
Issue reported by: jaspal.sandhu@gov.ab.ca@gov.ab.ca
Web component version: 1.32.1
Angular/React version: angular 4.2.1

# Info

`goab-badge` is out of alignment when compared to `goa-badge` (LTS version). This is also only an issue for Angular, React is unaffected.

## Code

```css
div.card-header {
  display: flex;
  flex-direction: row;
  gap: var(--goa-space-m);
  align-items: center;
  padding-bottom: var(--goa-space-s);
}

div.body-l {
  font: var(--goa-typography-body-l);
}
```

```html
<goab-container padding="compact">
  <div class="card-header">
    <div class="body-l"><a href="#">1234ABC</a></div>
    <goab-badge type="information" content="Draft"></goab-badge>
  </div>
</goab-container>
```

Just change `goab` to `goa` to test LTS version. The `<div class="body-l">` is simple because `goab-text` doesn't exist yet.

## goab Screenshot

![Image](https://github.com/user-attachments/assets/b5dd0168-8314-46ec-90af-4856e41c8489)

## goa Screenshot

![Image](https://github.com/user-attachments/assets/425509a1-bf16-47c5-aaee-e17e93ffe317)
