### ISSUE TITLE
Core SCSS Utilities

### ISSUE THREAD

**Issue by cjam** [GovAlta/ui-components#74]
It would be great to have a collection of utilities that could be used to create new styles that fit the design systems choices.  I generally do this on projects to give me the flexibility of creating custom styles for my components that still remain inline with the general design system.  Here are a few examples:

```scss
$space-increment: 8px;
$border-radius: 4px;
$default-duration: 500ms;

@mixin transition($property: background-color, $duration: $default-duration) {
  transition: $property $duration;
}

@function spacing($amounts...) {
  $toReturn: ();
  @each $amount in $amounts {
    $toReturn: list.append($toReturn, $amount * $space-increment);
  }
  @return $toReturn;
}

@mixin rounded($amounts...) {
  $toReturn: ();
  @each $amount in $amounts {
    $toReturn: list.append($toReturn, $amount * $border-radius);
  }
  border-radius: $toReturn;
}

@mixin roundedTop($amount) {
  @include rounded($amount, $amount, 0, 0);
}
```

Which inside of some custom components style could be used like:

```scss
@import "path/to/utils.scss"

.card {
  @include roundedTop(1);  // rounded top 1
  @include transition(border-color);
    border: 1px solid light;
  &:hover{
    border-color: blue;
  }
}

.header {
  padding: spacing(1.5, 0, 1, 2);  // Defining spacing for all sides 
}

.content {
  padding: spacing(1);  // equal spacing on all sides
}
```

Perhaps these exist in some form somewhere.  Thought it might be useful though.
